# Generated by Django 3.2.25 on 2024-08-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_review', '0004_auto_20240817_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_number', models.CharField(max_length=100, unique=True)),
                ('spec_title', models.CharField(max_length=255)),
                ('spec_authority', models.CharField(max_length=100)),
                ('revision', models.CharField(max_length=50)),
            ],
        ),
    ]
