# Generated by Django 3.2.25 on 2024-08-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spec_review', '0005_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='specification_number',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='specification_title',
        ),
        migrations.AddField(
            model_name='requirement',
            name='specification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='spec_review.specification'),
            preserve_default=False,
        ),
    ]
