# Generated by Django 3.2.25 on 2024-08-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_review', '0006_auto_20240818_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='clause',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='requirement',
            name='page_number',
            field=models.IntegerField(default=0),
        ),
    ]
