# Generated by Django 3.2.25 on 2024-08-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_review', '0007_auto_20240821_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='specifications_pdfs/'),
        ),
    ]
