# Generated by Django 3.2.25 on 2024-08-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_review', '0008_specification_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='spec_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='specification',
            constraint=models.UniqueConstraint(fields=('spec_number', 'spec_title', 'revision'), name='unique_specification_revision'),
        ),
    ]
